# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [ ]:
import numpy as np
# Сгенерировать двумерного массива размерности (4, 7) со случайными числами от 0 до 20
arr=np.random.uniform(0, 20, (4, 7))

# Находим минимальное и максимальное значение в массиве
min_v=np.min(arr)
max_v=np.max(arr)

# Вычисляем коэффициенты a и b для преобразования ax+b
a=1 / (max_v - min_v)
b=-a * min_v

# Нормализация значений массива
normal=a*arr + b

print(normal)

[[0.27319881 0.06079039 0.15983089 0.73028661 0.02531085 0.91803791
  0.51769891]
 [0.1780848  0.27152075 0.02506612 0.56283308 0.70524412 0.13665128
  0.8695777 ]
 [0.79823743 0.2866978  0.8170698  0.79591592 0.59002612 0.35621784
  0.37757069]
 [0.01913157 0.         0.29838797 0.062254   0.07301974 1.
  0.26877008]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [ ]:
import numpy as np
matrix = np.random.randint(0, 11, (8, 10))
print(matrix)

# Нахождение строки с минимальной суммой значений
row_sums = np.sum(matrix, axis=1)
min_sum_row_index = np.argmin(row_sums)
min_sum_row = matrix[min_sum_row_index]

print("Строка с минимальной суммой значений:")
print(min_sum_row)
print("Индекс строки:", min_sum_row_index)

[[10  8  6  3  6  6  4  1 10  4]
 [ 7  0  9  6  5  0  3  2  4  0]
 [ 1  9  1  4  7 10  1  9  4  9]
 [ 1  6  2  5  2  4  2  3  3 10]
 [ 6  1  2  2 10  8  2 10  1  2]
 [ 1  3  2  1  2 10  1  6  4  3]
 [ 6  8  2  3  2  3  8  2  7  8]
 [ 7  0  8  4  1  4  7  0  8  0]]
Строка с минимальной суммой значений:
[ 1  3  2  1  2 10  1  6  4  3]
Индекс строки: 5


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [ ]:
import numpy as np

def euclidean_distance(vector1, vector2):
    return np.linalg.norm(vector1 - vector2)

# Пример
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

distance = euclidean_distance(vector1, vector2)
print(distance)

5.196152422706632


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [ ]:
import numpy as np

A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.array([[3, -1], [2, 1]])
C = np.array([[7, 21], [11, 8], [8, 4]])

X = np.linalg.solve(A, -np.dot(C, B))
print(X)

[[  7.  -4.]
 [ -6.   7.]
 [-11.  -8.]]


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [3]:
from google.colab import drive
import numpy as np

drive.mount('/content/drive')
data_path = "/content/drive/My Drive/Colab Notebooks/"

data = np.loadtxt(data_path + 'minutes_n_ingredients.csv',delimiter=',', dtype=np.int32, skiprows=1)
print(data[:5])


Mounted at /content/drive
[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [ ]:
mean = np.mean(data[:, 1:], axis=0)
minimum = np.min(data[:, 1:], axis=0)
maximum = np.max(data[:, 1:], axis=0)
median = np.median(data[:, 1:], axis=0)

print("среднее значение:", mean)
print("минимум:", minimum)
print("максимум:", maximum)
print("медиану:", median)

среднее значение: [2.16010017e+04 9.05528000e+00]
минимум: [0 1]
максимум: [2147483647         39]
медиану: [40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$.

In [ ]:
data = np.loadtxt(data_path + 'minutes_n_ingredients.csv',delimiter=',', dtype=np.int32, skiprows=1,usecols=(1, 2))
q75 = np.quantile(data[:, 0], q=0.75)
data[data[:, 0] > q75] = q75
print(data)

[[60 16]
 [25  7]
 [10  6]
 ...
 [65 15]
 [ 5  4]
 [65 65]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [ ]:

data = np.loadtxt(data_path + 'minutes_n_ingredients.csv',delimiter=',', dtype=np.int32, skiprows=1,usecols=(1, 2))
num_with_0 = np.count_nonzero(data == 0)
data[data == 0] = 1
print(num_with_0)

479


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [ ]:
data = np.loadtxt(data_path + 'minutes_n_ingredients.csv',delimiter=',', dtype=np.int32, skiprows=1,usecols=(0,1, 2))
u_recipes = np.unique(data[:, 0])
print(len(u_recipes))


100000


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [ ]:
data = np.loadtxt(data_path + 'minutes_n_ingredients.csv',delimiter=',', dtype=np.int32, skiprows=1,usecols=(0,1,2))
u_ingredients = np.unique(data[:, 1])
print(u_ingredients)
print(len(u_ingredients))

[         0          1          2          3          4          5
          6          7          8          9         10         11
         12         13         14         15         16         17
         18         19         20         21         22         23
         24         25         26         27         28         29
         30         31         32         33         34         35
         36         37         38         39         40         41
         42         43         44         45         46         47
         48         49         50         51         52         53
         54         55         56         57         58         59
         60         61         62         63         64         65
         66         67         68         69         70         71
         72         73         74         75         76         77
         78         79         80         81         82         83
         84         85         86         87         88       

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [ ]:
data = np.loadtxt(data_path + 'minutes_n_ingredients.csv',delimiter=',', dtype=np.int32, skiprows=1,usecols=(0,1,2))
f_data = data[data[:, 2] <= 5]
print(f_data)

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [ ]:
data = np.loadtxt(data_path + 'minutes_n_ingredients.csv',delimiter=',', dtype=np.int32, skiprows=1)
max_data=max(data[:,2]/data[:,1])
print(max_data)

inf


<ipython-input-12-f4e121d3bbbc>:2: RuntimeWarning: divide by zero encountered in divide
  max_data=max(data[:,2]/data[:,1])


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [ ]:
data = np.loadtxt(data_path + 'minutes_n_ingredients.csv',delimiter=',', dtype=np.int32, skiprows=1,usecols=(0,1,2))
topchik = np.argpartition(data[:, 0], -100)[-100:]
top = data[topchik, 1]
sr_data=np.mean(top)
print(sr_data)


156.62


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [ ]:

data = np.loadtxt(data_path + 'minutes_n_ingredients.csv',delimiter=',', dtype=np.int32, skiprows=1,usecols=(0,1,2))
idx=np.random.randint(data.shape[0],size=10)
data[idx,:]

array([[457968,     65,     14],
       [366847,    130,     11],
       [304244,      5,      7],
       [112617,     45,      6],
       [217315,     60,      2],
       [ 31652,     60,      8],
       [402174,    105,     14],
       [329474,     35,     18],
       [129166,    100,      4],
       [367708,     15,      8]], dtype=int32)

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [ ]:
data = np.loadtxt(data_path + 'minutes_n_ingredients.csv',delimiter=',', dtype=np.int32, skiprows=1,usecols=(0,1,2))
sr_recep = np.mean(data[:, 1])
s_indg=np.count_nonzero(data[:, 1] < sr_recep)
percent = 100*s_indg / data.shape[0]
print(percent)

99.949


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [4]:
import numpy as np
data = np.loadtxt(data_path + 'minutes_n_ingredients.csv',delimiter=',', dtype=np.int32, skiprows=1,usecols=(0,1,2))

simple_recipe = np.where((data[:, 1] <= 20) & (data[:, 2] <= 5), 1, 0)

# Объединение нового столбца с исходными данными
data_with_simple_recipe=np.column_stack((data, simple_recipe))
print(data_with_simple_recipe)
# Сохранение нового датасета в файл
np.savetxt('minutes_n_ingredients_with_simple_recipe.csv', data_with_simple_recipe, delimiter=',')



[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993    140     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [5]:
percent_simple = (simple_recipe == 1).mean() * 100
print(percent_simple)

9.552


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [ ]:
# Разделение рецептов на группы
short_recipes = data[data[:, 1] < 10]
standard_recipes = data[(data[:, 1] >= 10) & (data[:, 1] < 20)]
long_recipes = data[data[:, 1] >= 20]

# Максимальное количество рецептов в каждой группе
max_short_recipes = min(len(short_recipes), 10)
max_standard_recipes = min(len(standard_recipes), 10)
max_long_recipes = min(len(long_recipes), 10)

# Создание трехмерного массива
result = np.zeros((3, max_short_recipes + max_standard_recipes + max_long_recipes, 3))

# Заполнение трехмерного массива данными
result[0, :max_short_recipes, :] = short_recipes[:max_short_recipes]
result[1, :max_standard_recipes, :] = standard_recipes[:max_standard_recipes]
result[2, :max_long_recipes, :] = long_recipes[:max_long_recipes]

# Вывод формы полученного массива
print(result.shape)

(3, 30, 3)
